"""Cross-cutting utilities: exceptions, logging, filesystem helpers."""

from .exceptions import (
    AudioDecodeError,
    AudioFPError,
    AudioProcessingError,
    AuthenticationError,
    ConfigurationError,
    ConflictError,
    FFmpegNotFoundError,
    FingerprintCompatibilityError,
    ForbiddenError,
    JobError,
    MatchingError,
    NotFoundError,
    PayloadTooLargeError,
    StorageError,
    UnsupportedFormatError,
    ValidationError,
)
from .logging import configure_logging, get_logger, job_id_var, log_extra, request_id_var

__all__ = [
    "AudioDecodeError",
    "AudioFPError",
    "AudioProcessingError",
    "AuthenticationError",
    "ConfigurationError",
    "ConflictError",
    "FFmpegNotFoundError",
    "FingerprintCompatibilityError",
    "ForbiddenError",
    "JobError",
    "MatchingError",
    "NotFoundError",
    "PayloadTooLargeError",
    "StorageError",
    "UnsupportedFormatError",
    "ValidationError",
    "configure_logging",
    "get_logger",
    "job_id_var",
    "log_extra",
    "request_id_var",
]
